const Map<String, dynamic> tourDetailsStatic = {
  "success": true,
  "data": {
    "tourPurposes": [
      {
        "id": 1,
        "name": "Party Visit (Dealer/Payment)",
        "created_at": null,
        "updated_at": null,
        "deleted_at": null,
      },
      {
        "id": 2,
        "name": "Field Visit",
        "created_at": null,
        "updated_at": null,
        "deleted_at": null,
      },
      {
        "id": 3,
        "name": "Office Visit",
        "created_at": null,
        "updated_at": null,
        "deleted_at": null,
      },
      {
        "id": 4,
        "name": "Work from home",
        "created_at": null,
        "updated_at": null,
        "deleted_at": null,
      },
      {
        "id": 5,
        "name": "Other",
        "created_at": null,
        "updated_at": null,
        "deleted_at": null,
      },
    ],
    "vehicleTypes": [
      {
        "id": 1,
        "name": "Two Wheeler Personal",
        "created_at": null,
        "updated_at": null,
        "deleted_at": null,
      },
      {
        "id": 2,
        "name": "Four Wheeler Personal",
        "created_at": null,
        "updated_at": null,
        "deleted_at": null,
      },
      {
        "id": 3,
        "name": "Two Wheeler Company",
        "created_at": null,
        "updated_at": null,
        "deleted_at": null,
      },
      {
        "id": 4,
        "name": "Four Wheeler Company",
        "created_at": null,
        "updated_at": null,
        "deleted_at": null,
      },
      {
        "id": 5,
        "name": "Other",
        "created_at": null,
        "updated_at": null,
        "deleted_at": null,
      },
    ],
    "tourTypes": [
      {
        "id": 1,
        "name": "In Headquarter",
        "created_at": null,
        "updated_at": null,
        "deleted_at": null,
      },
      {
        "id": 2,
        "name": "Out of Headquarter",
        "created_at": null,
        "updated_at": null,
        "deleted_at": null,
      },
      {
        "id": 3,
        "name": "Tour with senior",
        "created_at": null,
        "updated_at": null,
        "deleted_at": null,
      },
      {
        "id": 4,
        "name": "Work from home",
        "created_at": null,
        "updated_at": null,
        "deleted_at": null,
      },
      {
        "id": 5,
        "name": "Farm Visit",
        "created_at": null,
        "updated_at": null,
        "deleted_at": null,
      },
    ],
  },
  "message": "Tour details fetch successfully",
};
